export interface ReferenceTemplateOptions {
  cssHref: string
  jsSrc: string
  title: string
}

export interface ReferenceCssOptions {
  target: 'css' | 'tw4'
  contractPath: string
  debugPath?: string | null
}

export function renderReferenceHtml(options: ReferenceTemplateOptions): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${options.title}</title>
    <link rel="stylesheet" href="${options.cssHref}" />
  </head>
  <body>
    <main class="g-shell g-project-default ref-root" data-g-debug-scope data-g-debug-label="Reference root" data-g-project-preset="default">
      <section class="g-full ref-hero" data-g-debug-scope data-g-debug-label="Scene A · hero">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Gerstner / living reference</p>
          <h1 class="g-display">The contract should be visible, not theoretical.</h1>
          <p class="g-prose">This page is generated by the CLI to prove shell behavior, aligned views, independent grids, rhythm, adaptive collections, scope overrides, and the dev inspector using the same CSS contract the project ships.</p>
        </div>
      </section>

      <section class="g-full ref-scene" data-g-debug-scope data-g-debug-label="Scene A · shell versus raw">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Scene A</p>
          <h2 class="g-heading">Shell versus raw grid</h2>
          <div class="ref-duo">
            <div class="ref-card g-stack-1">
              <p class="ref-label g-ui">g-shell</p>
              <div class="g-shell ref-demo-shell">
                <div class="g-content ref-rail">
                  <span>content zone</span>
                </div>
                <div class="g-breakout-r ref-bleed"><span>breakout</span></div>
              </div>
            </div>
            <div class="ref-card g-stack-1">
              <p class="ref-label g-ui">g</p>
              <div class="g ref-demo-raw">
                <div class="ref-raw-12 col-full">
                  <span>equal visible columns edge to edge</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="g-full ref-scene" data-g-debug-scope data-g-debug-label="Scene B · aligned views">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Scene B</p>
          <h2 class="g-heading">Aligned local views</h2>
          <div class="g-shell ref-demo-band">
            <div class="g-content g-view-6 ref-demo-view"><span>6-col approximate reinterpretation</span></div>
            <div class="g-content g-view-4 ref-demo-view alt"><span>4-col approximate reinterpretation</span></div>
            <div class="g-content g-view-2 ref-demo-view"><span>2-col approximate reinterpretation</span></div>
          </div>
        </div>
      </section>

      <section class="g-full ref-scene" data-g-debug-scope data-g-debug-label="Scene C · independent view">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Scene C</p>
          <h2 class="g-heading">Independent local view</h2>
          <div class="g g-align-independent ref-independent" style="--g-cols: 5">
            <div class="col-full ref-pill">5-col local view that is intentionally not harmonic with the shell</div>
          </div>
        </div>
      </section>

      <section class="g-full ref-scene" data-g-debug-scope data-g-debug-label="Scene D · exact subgrid">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Scene D</p>
          <h2 class="g-heading">Exact subgrid inheritance</h2>
          <div class="g-shell ref-subgrid-parent">
            <div class="g-content ref-subgrid-window">
              <div class="g-sub ref-subgrid-child">
                <div class="ref-pill">zero drift inherited lines</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="g-full ref-scene" data-g-debug-scope data-g-debug-label="Scene E · breakout" data-testid="scene-breakout">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Scene E</p>
          <h2 class="g-heading">Asymmetrical breakout and line placement</h2>
        </div>
        <div class="g-breakout-l ref-media"><span>g-breakout-l</span></div>
        <div class="g-breakout-r ref-media alt"><span>g-breakout-r</span></div>
        <div class="col-from-8 ref-media strong"><span>col-from-8</span></div>
      </section>

      <section class="g-full ref-scene" data-g-debug-scope data-g-debug-label="Scene F · typography">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Scene F</p>
          <h2 class="g-heading">Foundation and typography</h2>
          <div class="ref-card g-stack-2">
            <p class="g-prose">Prose uses the unitless <code>--g-prose</code> value derived from <code>--g-rhythm</code> and <code>--g-type-base</code>. It scales with browser text size instead of freezing at a fixed rem line-height.</p>
            <p class="g-ui">UI breaks page rhythm on purpose. It lives on tighter component spacing.</p>
          </div>
        </div>
      </section>

      <section class="g-full ref-scene" data-g-debug-scope data-g-debug-label="Scene G · adaptive collections">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Scene G</p>
          <h2 class="g-heading">Adaptive collections</h2>
          <div class="g-fit ref-collection">
            <div class="ref-card">g-fit</div>
            <div class="ref-card alt">g-fit</div>
            <div class="ref-card">g-fit</div>
            <div class="ref-card alt">g-fit</div>
          </div>
          <div class="g-fill ref-collection">
            <div class="ref-card">g-fill</div>
            <div class="ref-card alt">g-fill</div>
            <div class="ref-card">g-fill</div>
          </div>
        </div>
      </section>

      <section class="g-full ref-scene" data-g-debug-scope data-g-debug-label="Scene H · scope overrides">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Scene H</p>
          <h2 class="g-heading">Scope overrides</h2>
          <div class="ref-duo">
            <section class="g-shell g-project-default ref-card" data-g-debug-scope data-g-debug-label="Scope override · default" data-g-project-preset="default">
              <div class="g-content g-stack-1">
                <p class="ref-label g-ui">default scope</p>
                <p class="g-prose">Uses the root contract.</p>
              </div>
            </section>
            <section class="g-shell g-project-campaign ref-card" data-g-debug-scope data-g-debug-label="Scope override · campaign" data-g-project-preset="campaign">
              <div class="g-content g-stack-1">
                <p class="ref-label g-ui">campaign scope</p>
                <p class="g-prose">Overrides frame, gutter, measure, and scale ratio locally.</p>
              </div>
            </section>
          </div>
        </div>
      </section>

      <section class="g-full ref-scene" data-g-debug-scope data-g-debug-label="Scene I · debug export">
        <div class="g-content g-stack-2">
          <p class="ref-kicker g-ui">Scene I</p>
          <h2 class="g-heading">Debug and export</h2>
          <div class="ref-card g-stack-1">
            <p class="g-prose">Turn the overlay on, inspect a scope, and export the live contract from the panel. The badge should surface human labels, not raw token names.</p>
            <p class="g-ui">Alt+G opens the panel. Alt+click pins the current scope.</p>
          </div>
        </div>
      </section>
    </main>

    <script type="module" src="${options.jsSrc}"></script>
  </body>
</html>
`
}

export function renderReferenceCss(options: ReferenceCssOptions): string {
  const debugImport = options.debugPath ? `@import "${options.debugPath}";\n` : ''
  const gerstnerImport =
    options.target === 'tw4'
      ? `@import "tailwindcss";\n@import "gerstner/tw4";\n@source "../node_modules/gerstner";`
      : `@import "gerstner/css";`

  return `${gerstnerImport}
@import "${options.contractPath}";
${debugImport}
:root {
  color-scheme: dark;
  background: #0a0a0a;
  color: #f3f3f3;
  font-family: Inter, ui-sans-serif, system-ui, sans-serif;
}

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  min-height: 100%;
}

body {
  background:
    radial-gradient(circle at top, rgba(255, 255, 255, 0.08), transparent 30%),
    #0a0a0a;
}

.ref-root {
  padding-block-end: 6rem;
}

.ref-hero {
  min-block-size: 100svh;
  display: grid;
  align-content: center;
}

.ref-scene {
  padding-block: 3rem;
}

.ref-kicker,
.ref-label {
  margin: 0;
  opacity: 0.72;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.ref-duo,
.ref-demo-band,
.ref-collection {
  display: grid;
  gap: var(--g-gutter);
}

.ref-duo {
  grid-template-columns: repeat(auto-fit, minmax(min(24rem, 100%), 1fr));
}

.ref-card,
.ref-media,
.ref-pill,
.ref-rail,
.ref-raw-12,
.ref-demo-view,
.ref-subgrid-window,
.ref-subgrid-child {
  border: 1px solid rgba(255, 255, 255, 0.12);
  border-radius: 1.25rem;
  background: rgba(255, 255, 255, 0.04);
  padding: 1.25rem;
}

.ref-media,
.ref-demo-view,
.ref-rail,
.ref-raw-12,
.ref-subgrid-child {
  min-block-size: 8rem;
  display: grid;
  place-items: center;
}

.ref-media.strong,
.ref-demo-view.alt,
.ref-card.alt {
  background: rgba(255, 255, 255, 0.08);
}

.ref-demo-shell,
.ref-demo-raw,
.ref-subgrid-parent {
  min-block-size: 14rem;
}

.ref-demo-band {
  gap: 1rem;
}

.ref-demo-view span,
.ref-media span,
.ref-rail span,
.ref-pill,
.ref-raw-12 span,
.ref-subgrid-child {
  font-size: var(--g-scale--1);
  line-height: 1.1;
  text-align: center;
}

.ref-independent {
  gap: var(--g-gutter);
}

.ref-subgrid-window {
  grid-column: 3 / 11;
  display: grid;
  grid-template-columns: subgrid;
}

.ref-subgrid-child {
  grid-column: 1 / -1;
}

.ref-collection {
  margin-block-start: 1rem;
}

.ref-collection > * {
  min-block-size: 8rem;
}

code {
  font: inherit;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  background: rgba(255, 255, 255, 0.08);
  padding: 0.1rem 0.35rem;
  border-radius: 0.45rem;
}
`
}

export function renderReferenceJs(options: { debugScriptPath?: string | null }): string {
  const debugImport = options.debugScriptPath ? `import "${options.debugScriptPath}"\n\n` : ''
  return `${debugImport}document.documentElement.dataset.gerstnerReference = 'true'\n`
}
