packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@playwright/test': 1.59.1
  '@types/node': 25.6.0
  '@tailwindcss/vite': 4.2.2
  syncpack: 14.3.0
  tailwindcss: 4.2.2
  tsdown: 0.21.7
  typescript: 6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
