export interface ContractTemplateOptions {
  cols: number
  gutter: string
  frame: string
  maxWidth: string
  min: string
  typeBase: string
  baseline: string
  leadingSteps: number
  scaleRatio: number
  measure: string
}

export function renderContractCss(options: ContractTemplateOptions): string {
  return `/*
  Gerstner project contract
  Generated by @gerstner/cli

  This file owns project-level variables only.
  Derived values such as --g-rhythm, --g-prose, --g-col-unit-raw,
  and --g-stride stay inside the core engine.
*/

:root {
  --g-cols: ${options.cols};
  --g-gutter: ${options.gutter};
  --g-frame: ${options.frame};
  --g-max-width: ${options.maxWidth};
  --g-min: ${options.min};
  --g-type-base: ${options.typeBase};
  --g-baseline: ${options.baseline};
  --g-leading-steps: ${options.leadingSteps};
  --g-scale-ratio: ${options.scaleRatio};
  --g-measure: ${options.measure};
}
`
}
