export interface ContractTemplateOptions {
  baseline: string
  proseLeading: [number, number, number]
  scaleRatio: number
  measure: string
  frame: string
  cols: number
  gutter: string
  maxWidth: string
  minWidth: string
  lattice: number
  fitMin: string
  breakout: string
}

export function renderContractCss(options: ContractTemplateOptions): string {
  const [prose1, prose2, prose3] = options.proseLeading

  return `/*
  Gerstner project contract
  Generated by @gerstner/cli

  This file owns project-level variables.
  It does not replace @gerstner/core.
*/

:root {
  --g-baseline: ${options.baseline};
  --g-scale-ratio: ${options.scaleRatio};
  --g-measure: ${options.measure};
  --g-min-width: ${options.minWidth};

  --g-lattice: ${options.lattice};
  --g-cols: ${options.cols};
  --g-gap: ${options.gutter};
  --g-page-pad: ${options.frame};
  --g-shell-edge-min: ${options.frame};
  --g-breakout: ${options.breakout};
  --g-content-max: ${options.maxWidth};
  --g-fit-min: ${options.fitMin};

  --g-prose-leading-1: ${prose1};
  --g-prose-leading-2: ${prose2};
  --g-prose-leading-3: ${prose3};

  --g-leading-tight: 1.08;
  --g-leading-body: 1.45;
  --g-leading-prose: ${prose2};

  --g-text-body: clamp(0.98rem, 0.95rem + 0.15vw, 1.08rem);
  --g-text-prose: clamp(1rem, 0.96rem + 0.18vw, 1.15rem);
  --g-text-display: clamp(2.2rem, 1.55rem + 2.8vw, 5.5rem);
}

@media (width >= 48rem) {
  :root {
    --g-gap: calc(${options.gutter} * 1.25);
    --g-page-pad: calc(${options.frame} * 1.5);
    --g-shell-edge-min: calc(${options.frame} * 1.25);
  }
}

@media (width >= 80rem) {
  :root {
    --g-gap: calc(${options.gutter} * 1.5);
    --g-page-pad: calc(${options.frame} * 2);
    --g-shell-edge-min: calc(${options.frame} * 1.5);
  }
}
`
}
