export function renderPresetCss(): string {
  return `/*
  Gerstner project presets
  Generated by @gerstner/cli

  These are project-owned overrides on top of gerstner core presets.
*/

.g-project-default,
[data-g-project-preset="default"] {
  --g-cols: 12;
  --g-gutter: clamp(0.875rem, 2.2vw, 1.5rem);
  --g-frame: clamp(1rem, 5dvw, 5rem);
  --g-max-width: 90rem;
  --g-min: 16rem;
  --g-leading-steps: 3;
  --g-scale-ratio: 1.25;
  --g-measure: 70ch;
}

.g-project-compact,
[data-g-project-preset="compact"] {
  --g-cols: 8;
  --g-gutter: clamp(0.75rem, 1.8vw, 1rem);
  --g-frame: clamp(0.875rem, 4dvw, 3rem);
  --g-max-width: 72rem;
  --g-min: 14rem;
  --g-leading-steps: 3;
  --g-scale-ratio: 1.2;
  --g-measure: 62ch;
}

.g-project-campaign,
[data-g-project-preset="campaign"] {
  --g-cols: 12;
  --g-gutter: clamp(1rem, 2.5vw, 2rem);
  --g-frame: clamp(1rem, 8dvw, 8rem);
  --g-max-width: 96rem;
  --g-min: 18rem;
  --g-leading-steps: 3;
  --g-scale-ratio: 1.333;
  --g-measure: 64ch;
}
`
}
