export function renderPresetCss(): string {
  return `/*
  Gerstner project presets
  Generated by @gerstner/cli

  These are variable-only helpers.
*/

.g-preset-editorial,
[data-g-preset="editorial"] {
  --g-cols: 12;
  --g-content-max: 72rem;
  --g-breakout: clamp(0rem, 4vw, 5rem);
  --g-fit-min: 16rem;
}

.g-preset-compact,
[data-g-preset="compact"] {
  --g-cols: 8;
  --g-content-max: 64rem;
  --g-breakout: clamp(0rem, 2vw, 2.5rem);
  --g-fit-min: 12rem;
  --g-gap: 0.875rem;
}

.g-preset-campaign,
[data-g-preset="campaign"] {
  --g-cols: 12;
  --g-content-max: 82rem;
  --g-breakout: clamp(1rem, 6vw, 8rem);
  --g-fit-min: 18rem;
}
`
}
