export interface ReferenceTemplateOptions {
  cssHref: string
  jsSrc: string
  title: string
}

export function renderReferenceHtml(options: ReferenceTemplateOptions): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${options.title}</title>
    <link rel="stylesheet" href="${options.cssHref}" />
  </head>
  <body>
    <main class="g-shell ref-shell g-type-body g-preset-editorial" data-g-debug-scope data-g-debug-label="Reference root">
      <header class="g-full ref-scene g-stack">
        <div>
          <p class="ref-kicker">Gerstner / reference</p>
          <h1 class="g-type-display">The contract should be visible, not theoretical.</h1>
          <p class="g-type-prose">This page is generated by the CLI to prove the current system contract with real DOM, real CSS, and optional debug wiring.</p>
        </div>
      </header>

      <section class="g-full g-shell ref-scene" data-g-debug-scope data-g-debug-label="Shell and breakout proof">
        <div class="g-content ref-card g-stack">
          <p class="ref-kicker">Zones</p>
          <h2>Shell, content, and breakouts</h2>
          <p>The shell owns the outer frame. Inner composition should use raw grids and view helpers.</p>
        </div>
        <div class="g-breakout-r ref-media">Breakout</div>
      </section>

      <section class="g-content ref-scene g-stack" data-g-debug-scope data-g-debug-label="Fit and fill proof">
        <p class="ref-kicker">Adaptivity</p>
        <div class="g-fit ref-metrics">
          <div class="ref-card">Load</div>
          <div class="ref-card alt">Latency</div>
          <div class="ref-card">Parity</div>
          <div class="ref-card alt">Coverage</div>
        </div>
      </section>
    </main>

    <script type="module" src="${options.jsSrc}"></script>
  </body>
</html>
`
}

export function renderReferenceCss(options: { contractPath: string; presetsPath: string; debugPath?: string | null }): string {
  const debugImport = options.debugPath ? `@import "${options.debugPath}";\n` : ''

  return `@import "@gerstner/core";
@import "${options.contractPath}";
@import "${options.presetsPath}";
${debugImport}
:root {
  color-scheme: dark;
  background: #0a0a0a;
  color: #f3f3f3;
  font-family: Inter, ui-sans-serif, system-ui, sans-serif;
}

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  min-height: 100%;
}

body {
  background:
    radial-gradient(circle at top, rgba(255, 255, 255, 0.08), transparent 30%),
    #0a0a0a;
}

.g-stack {
  display: grid;
  gap: max(0.75rem, calc(var(--g-baseline, 0.25rem) * 3));
}

.g-type-body {
  font-size: var(--g-text-body);
  line-height: var(--g-leading-body);
}

.g-type-prose {
  font-size: var(--g-text-prose);
  line-height: var(--g-leading-prose);
  max-width: var(--g-measure, 72ch);
}

.g-type-display {
  font-size: var(--g-text-display);
  line-height: var(--g-leading-tight);
  margin: 0;
}

.ref-shell {
  padding-block: 4rem 6rem;
}

.ref-scene {
  padding-block: 2rem;
}

.ref-kicker {
  margin: 0 0 0.5rem;
  opacity: 0.72;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-size: 0.8rem;
}

.ref-card,
.ref-media {
  border: 1px solid rgba(255, 255, 255, 0.12);
  border-radius: 1.25rem;
  background: rgba(255, 255, 255, 0.04);
  padding: 1.25rem;
}

.ref-media {
  min-height: 18rem;
  display: grid;
  place-items: center;
  background: linear-gradient(135deg, rgba(255,255,255,0.08), rgba(255,255,255,0.02));
}

.ref-metrics {
  gap: var(--g-gap);
}

.alt {
  background: rgba(255, 255, 255, 0.08);
}
`
}

export function renderReferenceJs(options: { debugScriptPath?: string | null }): string {
  const debugImport = options.debugScriptPath ? `import "${options.debugScriptPath}"\n\n` : ''
  return `${debugImport}document.documentElement.dataset.gerstnerReference = 'true'\n`
}
